### ISSUE TITLE
Trouver un IDE Web adapté (simple + intégration de Git)

### ISSUE THREAD

**Issue by stephanedaviet** [code-academie/website#1]
Tenter de trouver un outil adapté pour le développement dans le cadre de la Code Académie, idéalement en mode Web. Pistes : https://www.slant.co/topics/713/~best-cloud-ides et Mozilla Thimble.

**Comment by stephane-daviet-maif** [comment]
# Cloud9
* Puissant mais presque trop. Peut faire énormément de choses, possiblement confusant pour les élèves,
* Intégration de Git en mode ligne de commande.

# CodeTasty
* Pourri…

# Codenvy
* Sans doute encore plus pluissant que Cloud9,
* Exemple de base basé sur DotNet ?!,
* Intégration GUI de Git.

# CodeAnywhere
* Très simple dans la prise en main,
* Intégration Git un poil ardue (ligne de commande).

# Mozilla Thimble
* Hyper simple,
* Aucune intrégration Git.

# CodePen
* Un peu plus puissant que Thimble,
* Aucune intégration Git.
