### ISSUE TITLE
Créer une github page codeadademie.github.io

### ISSUE THREAD

**Issue by davidFR** [code-academie/website#2]
L'idée est de montrer comment créer une github pages au groupe afin qu'ils publient leurs sites.
https://pages.github.com/
On pourrait également leur donner accès à ce repository avec un sous répertoire "blog" où chacun crée une section div dans la page (ou une page dédiée) dans laquelle ils mettent leur avancement.

**Comment by stephane-daviet-maif** [comment]
Je vais vous faire un petit debrief de ce qu'on a fait mardi, mais on a abordé ce point.
